In [1]:
import torch as tf

In [2]:
x = tf.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
Y = tf.ones((2,3,4))
Y

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
Z = tf.tensor([[2,1,3,4],[1,3,2,4],[1,2,3,4]])
Z

tensor([[2, 1, 3, 4],
        [1, 3, 2, 4],
        [1, 2, 3, 4]])

In [8]:
x = tf.tensor([1.0,2,4,8])
y = tf.tensor([2.0,4,8,16])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  6., 12., 24.]),
 tensor([-1., -2., -4., -8.]),
 tensor([  2.,   8.,  32., 128.]),
 tensor([0.5000, 0.5000, 0.5000, 0.5000]),
 tensor([1.0000e+00, 1.6000e+01, 6.5536e+04, 2.8147e+14]))

In [9]:
tf.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [10]:
x = tf.arange(12,dtype=tf.float32).reshape((3,4))
y = tf.tensor([[2.0,1,2,3],[1,3,2,4],[1,2,3,4]])
tf.cat([x,y],dim=0),tf.cat([x,y],dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  2.,  3.],
         [ 1.,  3.,  2.,  4.],
         [ 1.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  3.,  2.,  4.],
         [ 8.,  9., 10., 11.,  1.,  2.,  3.,  4.]]))

In [11]:
x == y

tensor([[False,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
x.sum()

tensor(66.)

In [13]:
a = tf.arange(3).reshape((3,1))
b = tf.arange(2).reshape((1,2))
a,b,a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [14]:
x[-1]

tensor([ 8.,  9., 10., 11.])

In [15]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
X[0:2,:] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [18]:
import os 
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178000\n')
    f.write('NA,NA,140000\n')

In [19]:
import pandas as pd
data = pd.read_csv(data_file)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178000
3       NaN   NaN  140000

In [20]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
inputs,outputs

(   NumRooms Alley
 0       3.0  Pave
 1       2.0   NaN
 2       4.0   NaN
 3       3.0   NaN,
 0    127500
 1    106000
 2    178000
 3    140000
 Name: Price, dtype: int64)

In [21]:
inputs = pd.get_dummies(inputs,dummy_na = True)
inputs = inputs.astype('float32')
inputs

   NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0

In [22]:
x = tf.tensor(inputs.values)
y = tf.tensor(outputs.values)
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]]),
 tensor([127500, 106000, 178000, 140000]))

In [23]:
import torch as tf
x = tf.tensor([3.0])
y = tf.tensor([4.0])
x+y,x-y,x*y,x/y,x**y

(tensor([7.]), tensor([-1.]), tensor([12.]), tensor([0.7500]), tensor([81.]))

In [26]:
x = tf.arange(12)
x[3],x,len(x),x.shape

(tensor(3),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 12,
 torch.Size([12]))

In [27]:
A = tf.arange(20).reshape(4,5)
A,A.T

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  5, 10, 15],
         [ 1,  6, 11, 16],
         [ 2,  7, 12, 17],
         [ 3,  8, 13, 18],
         [ 4,  9, 14, 19]]))

In [33]:
X = tf.arange(24).reshape(2,3,4)
Y = tf.arange(24, 48).reshape(2, 3, 4)
X,Y,X+Y, X*Y

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]],

         [[36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47]]]),
 tensor([[[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]],

         [[48, 50, 52, 54],
          [56, 58, 60, 62],
          [64, 66, 68, 70]]]),
 tensor([[[   0,   25,   52,   81],
          [ 112,  145,  180,  217],
          [ 256,  297,  340,  385]],

         [[ 432,  481,  532,  585],
          [ 640,  697,  756,  817],
          [ 880,  945, 1012, 1081]]]))

In [35]:
A = tf.tensor([[0.0,1.0],[2.0,3.0]])
x = tf.tensor([2.0,3.0])
A,x,A*x, tf.mv(A,x)

(tensor([[0., 1.],
         [2., 3.]]),
 tensor([2., 3.]),
 tensor([[0., 3.],
         [4., 9.]]),
 tensor([ 3., 13.]))

In [ ]:
import torch as tf
A = tf.arange(20).reshape(4,5)
B = tf.arange(20,40).reshape(5,4)
tf.mm(A,B),A@B

(tensor([[ 320,  330,  340,  350],
         [1020, 1055, 1090, 1125],
         [1720, 1780, 1840, 1900],
         [2420, 2505, 2590, 2675]]),
 tensor([[ 320,  330,  340,  350],
         [1020, 1055, 1090, 1125],
         [1720, 1780, 1840, 1900],
         [2420, 2505, 2590, 2675]]))

In [46]:
u = tf.tensor([0.0,1.0,2.0,3.0])
tf.abs(u).sum()
a = tf.arange(24,dtype = tf.float32).reshape(2,3,4)
tf.norm(a)

tensor(65.7571)

In [13]:
import torch
x = torch.arange(4.0)
x.requires_grad_(True)
x.grad
y = 2 * torch.dot(x,x)
y.backward()
x.grad
x.grad == 4*x
x.grad.zero_()
y = x.sum()
y.backward()
x.grad
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [15]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b *2 
    if b.sum() > 0:
        c = b
    else:
        c = 100 *b
    return c
a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()  
a.grad == d/a

tensor(True)